
import { chewy } from "./ui/fonts";
import { Foother } from "@/components/Foother";
import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${chewy.className} antialiased`}>
        {children}
        
      </body>
    </html>
  );
}
